# Tensors:
  "A '***tensor***' is a generalisation of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as '***n-dimensional arrays of base datatypes***'"
* Tensors are a fundamental part of 'TensorFlow' (therefore the name), as Tensors are passed around and manipulated throughout the program. Each tensor represents a partially define computation that will eventually output a value. 
* Tensorflow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of this graph allow for different results to be generated.

Each tensor has a possible data size and shape.
* Think about tensors being more like a 'vector' (i.e. it isn't bound by a specific set of rules or coordinates)
* A vector can have infinite dimensions.

**Data Types for Tensors:**
* float32
* int32
* string
* etc.

**Shapes of Tensors:**
* Represent the dimension of data

# Creating Tensors:
Below is an example of creating a Tensor in TensorFlow:

In [93]:
import tensorflow as tf #Importing TensorFlow to the session

# Examples of a few different data types as Tensors:

# General Structure:
# [Variable name] = tf.variable([Data], tf.[data-type])

string = tf.Variable("This is a string", tf.string)
number = tf.Variable(345, tf.int16)
floating = tf.Variable(5.376, tf.float64)

# Rank/Degree of Tensors
  Another word for rank in TensorFlow is degree, and this just signifies the amount of 'dimensions' within the Tensor. The above Tensors are what would be considered as '***rank 0***', which are also referred to as ***scalar*** values.
* **Scalar Values:**
  * Having one value
* **Vector Values:**
  * Having multiple values
* **Matrices:**
  * Having multiple Vectors

Rank can be seen within the square brackets, where you can have as many values as you wish within each one, although 1 ***Rank/Degree*** is just a set of square brackets.

Essentially, the more lists you have inside other lists, the more ranks/degrees you have.

* In the below examples, I will create some Tensors with multiple dimensions

In [94]:
import tensorflow as tf #importing TensorFlow to the session

# Examples of a few different Ranks/Degrees of Tensors

# General Structure:
# [Variable Name] = tf.Variable([[Data1],[Data2]], [[Data3],[Data4]], tf.[data-type])

rank1_tensor = tf.Variable(["Test", "Hello, World!"], tf.string)
rank2_tensor = tf.Variable([["Test", "test"], ["Hello,", "World"]], tf.string)

# How to determine the rank of a Tensor:
You can look at the deepest nested list (how many lists are there going from most nested to the parent), or you can use the command below:

In [95]:
import tensorflow as tf #importing TensorFlow into the session

#Example on how to determine the rank of a tensor:

#General Structure:
# tf.rank([variable-name])

tf.rank(rank2_tensor)
#In this example, the 'numpy' field shows the rank of the Tensor

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensors:
The shape of each tensor is simply the amount of elements in each dimension. TenserFlow will attempt to call the shape of Tensors, although sometimes it can be unknown.

In [96]:
import tensorflow as tf #importing TensorFlow into the session

#Example on how to determine the shape of a Tensor

#General Structure:
#[variable-name].shape

rank2_tensor.shape
#In this example, there are 2 lists, and 2 elements in each of those lists

TensorShape([2, 2])

# Changing Shape:
You often have to change the shape of a Tensor in TensorFlow. 
* Many different shapes that can represent the same number of elements.
* **Flattening**   
  * Getting all the elements from a multi-rank Tensor, and put it in a '***Rank 1***' tensor.


In [97]:
import tensorflow as tf #Importing TensorFlow into the session

tensor1 = tf.ones([1,2,3]) #Make a Tensor with just ones, with a shape of [1,2,3]
tensor2 = tf.reshape(tensor1, [2,3,1]) #Reshape the Tensor into the shape [2,3,1]
tensor3 = tf.reshape(tensor1, [3, -1]) #-1 infers what the value should be. i.e. 3 lists, where the elements are distributed evenly.
                                       # this will reshape the Tensor to [3,2]

Now here are the different results from the above:

In [98]:
print("Tensor 1:")
print(tensor1) # 1 interior list, 2 lists inside of that interior list, and 3 objects in each list

print("\nTensor 2")
print(tensor2) # 2 interior lists, each with 3 lists within it, and 1 value in each list.

print("\nTensor3") 
print(tensor3) # 3 lists, each having 2 values

Tensor 1:
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

Tensor 2
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

Tensor3
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of Tensors:
There are a large variety of Tensors, although these are the most commonly used:
* Variable
* Constant
* Placeholder
* SparseTensor

All of these, with the exception of a Variable are immutable (i.e. cannot be changed during the operation of a program)

Therefore you should use the ***Variable*** Tensor if you want to change the value during operation.

# Evaluating Tensors:
There will be times where you would need to get the value of a Tensor. As Tensors represent partially computed data, it is sometimes necessary to run a ***session*** to evaluate the data.

Here is the simplest way of doing so.

In [ ]:
import tensorflow as tf

with tf.Session() as sess: # creates a session using the 'default graph'
    tensor1.eval() #change the variable name with the variable in question.eval()

# Reshaping a Tensor:


In [99]:
import tensorflow as tf #importing tensorflow into the session
print(tf.version)

t = tf.zeros([5,5,5,5]) #create a Tensor with all zeros
print(t)



UsageError: Line magic function `%tensorflow_version` not found.
